# Site wide configuration

title: Yipeng Qin | Homepage
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Yipeng Qin
  avatar: profile.jpg
  bio: Lecturer/Assistant Professor <br/> Cardiff University <br/> Wales, UK
  email: qiny16@cardiff.ac.uk
  # Do not include the @ symbol in your Twitter username
  twitter: #username
  linkedin: yipengqin
  github: YipengQin
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: Yipeng_Qin
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: ojgWPpgAAAAJ
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "http://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: #yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
